// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gbbhrrdojuhxtmfxkldz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdiYmhycmRvanVoeHRtZnhrbGR6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc1MjI0MzIsImV4cCI6MjA2MzA5ODQzMn0.UY-rhXGXxfvpZyAHYZu5gGixwAHDOsRGygXIVXciaNc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);